backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  # EN menu pages (excluding _index.md)
  - name: "en_menu"
    label: "Menu (EN)"
    folder: "content/en/menu"
    create: true
    slug: "{{slug}}"
    filter:
      field: "hidden"
      value: false
    fields:
      - { name: "title", label: "Title" }
      - { name: "category", label: "Category", widget: "string" }
      - { name: "items", label: "Items", widget: "list", fields: [
          { name: "name", label: "Name" },
          { name: "description", label: "Description" },
          { name: "price", label: "Price" },
          { name: "image", label: "Image", widget: "image" }
        ], required: false }

  # AR menu pages (excluding _index.md)
  - name: "ar_menu"
    label: "Menu (AR)"
    folder: "content/ar/menu"
    create: true
    slug: "{{slug}}"
    filter:
      field: "hidden"
      value: false
    fields:
      - { name: "title", label: "Title" }
      - { name: "category", label: "Category", widget: "string" }
      - { name: "items", label: "Items", widget: "list", fields: [
          { name: "name", label: "Name" },
          { name: "description", label: "Description" },
          { name: "price", label: "Price" },
          { name: "image", label: "Image", widget: "image" }
        ], required: false }

  # EN menu index page (_index.md only)
  - name: "en_menu_index"
    label: "Menu Index (EN)"
    files:
      - file: "content/en/menu/_index.md"
        label: "Menu Index"
        name: "menu_index_en"
        fields:
          - { name: "title", label: "Title" }
          - { name: "description", label: "Description", widget: "text" }
          - { name: "keywords", label: "Keywords", widget: "string" }

  # AR menu index page (_index.md only)
  - name: "ar_menu_index"
    label: "Menu Index (AR)"
    files:
      - file: "content/ar/menu/_index.md"
        label: "Menu Index"
        name: "menu_index_ar"
        fields:
          - { name: "title", label: "Title" }
          - { name: "description", label: "Description", widget: "text" }
          - { name: "keywords", label: "Keywords", widget: "string" }
